name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check for '#skip' in commit message
        id: check_skip
        run: |
          if git log -1 --pretty=%B | grep -q '#skip'; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "it will skip tagging"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "it will tag"
          fi
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Notify Discord of Deployment
        if: ${{ github.event_name == 'push' }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          details: Deployment to production has been triggered by a push to the `main` branch.
      - name: Notify Discord of Failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          details: Deployment pipeline failed on branch `${{ github.ref }}`.

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && needs.simple_deployment_pipeline.outputs.skip == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Notify Discord of Tagging
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          details: A new tag has been pushed to the repository after successful deployment.
      - name: Notify Discord of Failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: error
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            details: Tagging pipeline failed after deployment on branch `${{ github.ref }}`.